version: '3.8'

services:
  server:
    image: eina-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  web:
    image: eina-web
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development

networks:
  default:
    driver: bridge