version: '3.8'

services:
  server:
    image: eina-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development

  web:
    image: eina-web
    build:
      context: ./client
      dockerfile: Dockerfile
      target: runner
    ports:
      - 3000:3000

networks:
  default:
    driver: bridge