---
name: "Deploy"

env:
    DOCKERFILE: Dockerfile

on:
    push:
        branches:
            - main

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                app:
                    - eina-web
                    - eina-server
                context:
                    - './client'
                    - './server'
                caprover_token:
                    - '${{ secrets.CAPROVER_CLIENT_APP_TOKEN }}'
                    - '${{ secrets.CAPROVER_SERVER_APP_TOKEN }}'
        steps:
            - uses: actions/checkout@v1

            - name: Set Environment Variables
              run: |
                  echo "IMAGE_NAME=${{ matrix.app }}" >> $GITHUB_ENV
                  echo "FULL_IMAGE_NAME=${{ matrix.app }}:$(date +%s)" >> $GITHUB_ENV
                  echo "CAPROVER_APP=${{ matrix.app }}" >> $GITHUB_ENV
                  echo "CONTEXT_DIR=${{ matrix.context }}" >> $GITHUB_ENV
            
            - name: Log in to the Container registry
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and Push Release to DockerHub
              shell: bash
              run: .github/scripts/build_and_push.sh

            - name: Deploy to CapRover
              uses: caprover/deploy-from-github@v1.1.2
              with:
                  server: ${{ secrets.CAPROVER_HOST }}
                  app: ${{ matrix.app }}
                  token: '${{ matrix.caprover_token }}'
                  image: '${{ env.FULL_IMAGE_NAME }}'
