name: "Deploy"

env:
    DOCKERFILE: Dockerfile

on:
    push:
        branches:
            - main

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                app:
                    - eina-web
                    - eina-server
                context:
                    - './client'
                    - './server'
        steps:
            - uses: actions/checkout@v1

            - name: Set Environment Variables
              run: |
                  echo "IMAGE_NAME=${{ matrix.app }}" >> $GITHUB_ENV
                  echo "FULL_IMAGE_NAME=${{ matrix.app }}:$(date +%s)" >> $GITHUB_ENV
                  echo "CAPROVER_APP=${{ matrix.app }}" >> $GITHUB_ENV
                  echo "CONTEXT_DIR=${{ matrix.context }}" >> $GITHUB_ENV
            
            - name: Set CapRover Token
              run: |
                  if [ "${{ matrix.app }}" == "eina-web" ]; then
                    echo "CAPROVER_TOKEN=${{ secrets.CAPROVER_CLIENT_APP_TOKEN }}" >> $GITHUB_ENV
                  elif [ "${{ matrix.app }}" == "eina-server" ]; then
                    echo "CAPROVER_TOKEN=${{ secrets.CAPROVER_SERVER_APP_TOKEN }}" >> $GITHUB_ENV
                  fi
            
            - name: Log in to the Container registry
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and Push Release to DockerHub
              shell: bash
              run: .github/scripts/build_and_push.sh

            - name: Deploy to CapRover
              uses: caprover/deploy-from-github@v1.1.2
              with:
                  server: ${{ secrets.CAPROVER_HOST }}
                  app: ${{ env.CAPROVER_APP }}
                  token: ${{ env.CAPROVER_TOKEN }}
                  image: ${{ env.FULL_IMAGE_NAME }}
